# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workflows/v1/timeseries.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tilebox.workflows.workflowsv1 import core_pb2 as workflows_dot_v1_dot_core__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dworkflows/v1/timeseries.proto\x12\x0cworkflows.v1\x1a\x17workflows/v1/core.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x01\n\x0cTimeInterval\x12\x39\n\nstart_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tstartTime\x12\x35\n\x08\x65nd_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x07\x65ndTime\x12\'\n\x0fstart_exclusive\x18\x03 \x01(\x08R\x0estartExclusive\x12#\n\rend_inclusive\x18\x04 \x01(\x08R\x0c\x65ndInclusive\"c\n\x11\x44\x61tapointInterval\x12(\n\x05start\x18\x01 \x01(\x0b\x32\x12.workflows.v1.UUIDR\x05start\x12$\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x12.workflows.v1.UUIDR\x03\x65nd\"\x90\x03\n\x16TimeseriesDatasetChunk\x12\x31\n\ndataset_id\x18\x01 \x01(\x0b\x32\x12.workflows.v1.UUIDR\tdatasetId\x12\x37\n\rcollection_id\x18\x02 \x01(\x0b\x32\x12.workflows.v1.UUIDR\x0c\x63ollectionId\x12?\n\rtime_interval\x18\x03 \x01(\x0b\x32\x1a.workflows.v1.TimeIntervalR\x0ctimeInterval\x12N\n\x12\x64\x61tapoint_interval\x18\x04 \x01(\x0b\x32\x1f.workflows.v1.DatapointIntervalR\x11\x64\x61tapointInterval\x12#\n\rbranch_factor\x18\x05 \x01(\x05R\x0c\x62ranchFactor\x12\x1d\n\nchunk_size\x18\x06 \x01(\x05R\tchunkSize\x12\x35\n\x17\x64\x61tapoints_per_365_days\x18\x07 \x01(\x03R\x14\x64\x61tapointsPer365Days\"\x86\x01\n\tTimeChunk\x12?\n\rtime_interval\x18\x01 \x01(\x0b\x32\x1a.workflows.v1.TimeIntervalR\x0ctimeInterval\x12\x38\n\nchunk_size\x18\x02 \x01(\x0b\x32\x19.google.protobuf.DurationR\tchunkSizeB\xb8\x01\n\x10\x63om.workflows.v1B\x0fTimeseriesProtoP\x01ZBgithub.com/tilebox/tilebox-go/protogen/go/workflows/v1;workflowsv1\xa2\x02\x03WXX\xaa\x02\x0cWorkflows.V1\xca\x02\x0cWorkflows\\V1\xe2\x02\x18Workflows\\V1\\GPBMetadata\xea\x02\rWorkflows::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workflows.v1.timeseries_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.workflows.v1B\017TimeseriesProtoP\001ZBgithub.com/tilebox/tilebox-go/protogen/go/workflows/v1;workflowsv1\242\002\003WXX\252\002\014Workflows.V1\312\002\014Workflows\\V1\342\002\030Workflows\\V1\\GPBMetadata\352\002\rWorkflows::V1'
  _globals['_TIMEINTERVAL']._serialized_start=138
  _globals['_TIMEINTERVAL']._serialized_end=344
  _globals['_DATAPOINTINTERVAL']._serialized_start=346
  _globals['_DATAPOINTINTERVAL']._serialized_end=445
  _globals['_TIMESERIESDATASETCHUNK']._serialized_start=448
  _globals['_TIMESERIESDATASETCHUNK']._serialized_end=848
  _globals['_TIMECHUNK']._serialized_start=851
  _globals['_TIMECHUNK']._serialized_end=985
# @@protoc_insertion_point(module_scope)
