# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: workflows/v1/automation.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2
import tilebox.datasets.tilebox.v1.id_pb2 as tilebox_dot_v1_dot_id__pb2
import tilebox.workflows.workflows.v1.automation_pb2 as workflows_dot_v1_dot_automation__pb2


class AutomationService(Protocol):
    async def list_storage_locations(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.StorageLocations:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_storage_location(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.StorageLocation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_storage_location(self, request: workflows_dot_v1_dot_automation__pb2.StorageLocation, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.StorageLocation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_storage_location(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_automations(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.Automations:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_automation(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.AutomationPrototype:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_automation(self, request: workflows_dot_v1_dot_automation__pb2.AutomationPrototype, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.AutomationPrototype:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_automation(self, request: workflows_dot_v1_dot_automation__pb2.AutomationPrototype, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.AutomationPrototype:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_automation(self, request: workflows_dot_v1_dot_automation__pb2.DeleteAutomationRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AutomationServiceASGIApplication(ConnectASGIApplication[AutomationService]):
    def __init__(self, service: AutomationService | AsyncGenerator[AutomationService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/workflows.v1.AutomationService/ListStorageLocations": Endpoint.unary(
                    method=MethodInfo(
                        name="ListStorageLocations",
                        service_name="workflows.v1.AutomationService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=workflows_dot_v1_dot_automation__pb2.StorageLocations,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_storage_locations,
                ),
                "/workflows.v1.AutomationService/GetStorageLocation": Endpoint.unary(
                    method=MethodInfo(
                        name="GetStorageLocation",
                        service_name="workflows.v1.AutomationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=workflows_dot_v1_dot_automation__pb2.StorageLocation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_storage_location,
                ),
                "/workflows.v1.AutomationService/CreateStorageLocation": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateStorageLocation",
                        service_name="workflows.v1.AutomationService",
                        input=workflows_dot_v1_dot_automation__pb2.StorageLocation,
                        output=workflows_dot_v1_dot_automation__pb2.StorageLocation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_storage_location,
                ),
                "/workflows.v1.AutomationService/DeleteStorageLocation": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteStorageLocation",
                        service_name="workflows.v1.AutomationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_storage_location,
                ),
                "/workflows.v1.AutomationService/ListAutomations": Endpoint.unary(
                    method=MethodInfo(
                        name="ListAutomations",
                        service_name="workflows.v1.AutomationService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=workflows_dot_v1_dot_automation__pb2.Automations,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_automations,
                ),
                "/workflows.v1.AutomationService/GetAutomation": Endpoint.unary(
                    method=MethodInfo(
                        name="GetAutomation",
                        service_name="workflows.v1.AutomationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_automation,
                ),
                "/workflows.v1.AutomationService/CreateAutomation": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateAutomation",
                        service_name="workflows.v1.AutomationService",
                        input=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                        output=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_automation,
                ),
                "/workflows.v1.AutomationService/UpdateAutomation": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateAutomation",
                        service_name="workflows.v1.AutomationService",
                        input=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                        output=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_automation,
                ),
                "/workflows.v1.AutomationService/DeleteAutomation": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteAutomation",
                        service_name="workflows.v1.AutomationService",
                        input=workflows_dot_v1_dot_automation__pb2.DeleteAutomationRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_automation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/workflows.v1.AutomationService"


class AutomationServiceClient(ConnectClient):
    async def list_storage_locations(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.StorageLocations:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStorageLocations",
                service_name="workflows.v1.AutomationService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=workflows_dot_v1_dot_automation__pb2.StorageLocations,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_storage_location(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.StorageLocation:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStorageLocation",
                service_name="workflows.v1.AutomationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=workflows_dot_v1_dot_automation__pb2.StorageLocation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_storage_location(
        self,
        request: workflows_dot_v1_dot_automation__pb2.StorageLocation,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.StorageLocation:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateStorageLocation",
                service_name="workflows.v1.AutomationService",
                input=workflows_dot_v1_dot_automation__pb2.StorageLocation,
                output=workflows_dot_v1_dot_automation__pb2.StorageLocation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_storage_location(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteStorageLocation",
                service_name="workflows.v1.AutomationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_automations(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.Automations:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAutomations",
                service_name="workflows.v1.AutomationService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=workflows_dot_v1_dot_automation__pb2.Automations,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_automation(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.AutomationPrototype:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAutomation",
                service_name="workflows.v1.AutomationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_automation(
        self,
        request: workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.AutomationPrototype:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateAutomation",
                service_name="workflows.v1.AutomationService",
                input=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                output=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_automation(
        self,
        request: workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.AutomationPrototype:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateAutomation",
                service_name="workflows.v1.AutomationService",
                input=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                output=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_automation(
        self,
        request: workflows_dot_v1_dot_automation__pb2.DeleteAutomationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAutomation",
                service_name="workflows.v1.AutomationService",
                input=workflows_dot_v1_dot_automation__pb2.DeleteAutomationRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class AutomationServiceSync(Protocol):
    def list_storage_locations(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.StorageLocations:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_storage_location(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.StorageLocation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_storage_location(self, request: workflows_dot_v1_dot_automation__pb2.StorageLocation, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.StorageLocation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_storage_location(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_automations(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.Automations:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_automation(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.AutomationPrototype:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_automation(self, request: workflows_dot_v1_dot_automation__pb2.AutomationPrototype, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.AutomationPrototype:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_automation(self, request: workflows_dot_v1_dot_automation__pb2.AutomationPrototype, ctx: RequestContext) -> workflows_dot_v1_dot_automation__pb2.AutomationPrototype:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_automation(self, request: workflows_dot_v1_dot_automation__pb2.DeleteAutomationRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class AutomationServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: AutomationServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/workflows.v1.AutomationService/ListStorageLocations": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListStorageLocations",
                        service_name="workflows.v1.AutomationService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=workflows_dot_v1_dot_automation__pb2.StorageLocations,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_storage_locations,
                ),
                "/workflows.v1.AutomationService/GetStorageLocation": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetStorageLocation",
                        service_name="workflows.v1.AutomationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=workflows_dot_v1_dot_automation__pb2.StorageLocation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_storage_location,
                ),
                "/workflows.v1.AutomationService/CreateStorageLocation": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateStorageLocation",
                        service_name="workflows.v1.AutomationService",
                        input=workflows_dot_v1_dot_automation__pb2.StorageLocation,
                        output=workflows_dot_v1_dot_automation__pb2.StorageLocation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_storage_location,
                ),
                "/workflows.v1.AutomationService/DeleteStorageLocation": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteStorageLocation",
                        service_name="workflows.v1.AutomationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_storage_location,
                ),
                "/workflows.v1.AutomationService/ListAutomations": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListAutomations",
                        service_name="workflows.v1.AutomationService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=workflows_dot_v1_dot_automation__pb2.Automations,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_automations,
                ),
                "/workflows.v1.AutomationService/GetAutomation": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetAutomation",
                        service_name="workflows.v1.AutomationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_automation,
                ),
                "/workflows.v1.AutomationService/CreateAutomation": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateAutomation",
                        service_name="workflows.v1.AutomationService",
                        input=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                        output=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_automation,
                ),
                "/workflows.v1.AutomationService/UpdateAutomation": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateAutomation",
                        service_name="workflows.v1.AutomationService",
                        input=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                        output=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_automation,
                ),
                "/workflows.v1.AutomationService/DeleteAutomation": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteAutomation",
                        service_name="workflows.v1.AutomationService",
                        input=workflows_dot_v1_dot_automation__pb2.DeleteAutomationRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_automation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/workflows.v1.AutomationService"


class AutomationServiceClientSync(ConnectClientSync):
    def list_storage_locations(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.StorageLocations:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStorageLocations",
                service_name="workflows.v1.AutomationService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=workflows_dot_v1_dot_automation__pb2.StorageLocations,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_storage_location(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.StorageLocation:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStorageLocation",
                service_name="workflows.v1.AutomationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=workflows_dot_v1_dot_automation__pb2.StorageLocation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_storage_location(
        self,
        request: workflows_dot_v1_dot_automation__pb2.StorageLocation,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.StorageLocation:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateStorageLocation",
                service_name="workflows.v1.AutomationService",
                input=workflows_dot_v1_dot_automation__pb2.StorageLocation,
                output=workflows_dot_v1_dot_automation__pb2.StorageLocation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_storage_location(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteStorageLocation",
                service_name="workflows.v1.AutomationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_automations(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.Automations:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAutomations",
                service_name="workflows.v1.AutomationService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=workflows_dot_v1_dot_automation__pb2.Automations,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_automation(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.AutomationPrototype:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetAutomation",
                service_name="workflows.v1.AutomationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_automation(
        self,
        request: workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.AutomationPrototype:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateAutomation",
                service_name="workflows.v1.AutomationService",
                input=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                output=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_automation(
        self,
        request: workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_automation__pb2.AutomationPrototype:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateAutomation",
                service_name="workflows.v1.AutomationService",
                input=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                output=workflows_dot_v1_dot_automation__pb2.AutomationPrototype,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_automation(
        self,
        request: workflows_dot_v1_dot_automation__pb2.DeleteAutomationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteAutomation",
                service_name="workflows.v1.AutomationService",
                input=workflows_dot_v1_dot_automation__pb2.DeleteAutomationRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
