# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tilebox.workflows.workflows.v1 import diagram_pb2 as workflows_dot_v1_dot_diagram__pb2


class DiagramServiceStub(object):
    """The diagram service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Render = channel.unary_unary(
                '/workflows.v1.DiagramService/Render',
                request_serializer=workflows_dot_v1_dot_diagram__pb2.RenderDiagramRequest.SerializeToString,
                response_deserializer=workflows_dot_v1_dot_diagram__pb2.Diagram.FromString,
                _registered_method=True)


class DiagramServiceServicer(object):
    """The diagram service
    """

    def Render(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiagramServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Render': grpc.unary_unary_rpc_method_handler(
                    servicer.Render,
                    request_deserializer=workflows_dot_v1_dot_diagram__pb2.RenderDiagramRequest.FromString,
                    response_serializer=workflows_dot_v1_dot_diagram__pb2.Diagram.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workflows.v1.DiagramService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workflows.v1.DiagramService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiagramService(object):
    """The diagram service
    """

    @staticmethod
    def Render(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.DiagramService/Render',
            workflows_dot_v1_dot_diagram__pb2.RenderDiagramRequest.SerializeToString,
            workflows_dot_v1_dot_diagram__pb2.Diagram.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
