# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: workflows/v1/job.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import tilebox.workflows.workflows.v1.core_pb2 as workflows_dot_v1_dot_core__pb2
import tilebox.workflows.workflows.v1.diagram_pb2 as workflows_dot_v1_dot_diagram__pb2
import tilebox.workflows.workflows.v1.job_pb2 as workflows_dot_v1_dot_job__pb2


class JobService(Protocol):
    async def submit_job(self, request: workflows_dot_v1_dot_job__pb2.SubmitJobRequest, ctx: RequestContext) -> workflows_dot_v1_dot_core__pb2.Job:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_job(self, request: workflows_dot_v1_dot_job__pb2.GetJobRequest, ctx: RequestContext) -> workflows_dot_v1_dot_core__pb2.Job:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_job_progress(self, request: workflows_dot_v1_dot_job__pb2.GetJobProgressRequest, ctx: RequestContext) -> workflows_dot_v1_dot_core__pb2.Job:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def retry_job(self, request: workflows_dot_v1_dot_job__pb2.RetryJobRequest, ctx: RequestContext) -> workflows_dot_v1_dot_job__pb2.RetryJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def cancel_job(self, request: workflows_dot_v1_dot_job__pb2.CancelJobRequest, ctx: RequestContext) -> workflows_dot_v1_dot_job__pb2.CancelJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def visualize_job(self, request: workflows_dot_v1_dot_job__pb2.VisualizeJobRequest, ctx: RequestContext) -> workflows_dot_v1_dot_diagram__pb2.Diagram:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def query_jobs(self, request: workflows_dot_v1_dot_job__pb2.QueryJobsRequest, ctx: RequestContext) -> workflows_dot_v1_dot_job__pb2.QueryJobsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_job_prototype(self, request: workflows_dot_v1_dot_job__pb2.GetJobPrototypeRequest, ctx: RequestContext) -> workflows_dot_v1_dot_job__pb2.GetJobPrototypeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def clone_job(self, request: workflows_dot_v1_dot_job__pb2.CloneJobRequest, ctx: RequestContext) -> workflows_dot_v1_dot_core__pb2.Job:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class JobServiceASGIApplication(ConnectASGIApplication[JobService]):
    def __init__(self, service: JobService | AsyncGenerator[JobService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/workflows.v1.JobService/SubmitJob": Endpoint.unary(
                    method=MethodInfo(
                        name="SubmitJob",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.SubmitJobRequest,
                        output=workflows_dot_v1_dot_core__pb2.Job,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.submit_job,
                ),
                "/workflows.v1.JobService/GetJob": Endpoint.unary(
                    method=MethodInfo(
                        name="GetJob",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.GetJobRequest,
                        output=workflows_dot_v1_dot_core__pb2.Job,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_job,
                ),
                "/workflows.v1.JobService/GetJobProgress": Endpoint.unary(
                    method=MethodInfo(
                        name="GetJobProgress",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.GetJobProgressRequest,
                        output=workflows_dot_v1_dot_core__pb2.Job,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_job_progress,
                ),
                "/workflows.v1.JobService/RetryJob": Endpoint.unary(
                    method=MethodInfo(
                        name="RetryJob",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.RetryJobRequest,
                        output=workflows_dot_v1_dot_job__pb2.RetryJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.retry_job,
                ),
                "/workflows.v1.JobService/CancelJob": Endpoint.unary(
                    method=MethodInfo(
                        name="CancelJob",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.CancelJobRequest,
                        output=workflows_dot_v1_dot_job__pb2.CancelJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.cancel_job,
                ),
                "/workflows.v1.JobService/VisualizeJob": Endpoint.unary(
                    method=MethodInfo(
                        name="VisualizeJob",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.VisualizeJobRequest,
                        output=workflows_dot_v1_dot_diagram__pb2.Diagram,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.visualize_job,
                ),
                "/workflows.v1.JobService/QueryJobs": Endpoint.unary(
                    method=MethodInfo(
                        name="QueryJobs",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.QueryJobsRequest,
                        output=workflows_dot_v1_dot_job__pb2.QueryJobsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.query_jobs,
                ),
                "/workflows.v1.JobService/GetJobPrototype": Endpoint.unary(
                    method=MethodInfo(
                        name="GetJobPrototype",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.GetJobPrototypeRequest,
                        output=workflows_dot_v1_dot_job__pb2.GetJobPrototypeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_job_prototype,
                ),
                "/workflows.v1.JobService/CloneJob": Endpoint.unary(
                    method=MethodInfo(
                        name="CloneJob",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.CloneJobRequest,
                        output=workflows_dot_v1_dot_core__pb2.Job,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.clone_job,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/workflows.v1.JobService"


class JobServiceClient(ConnectClient):
    async def submit_job(
        self,
        request: workflows_dot_v1_dot_job__pb2.SubmitJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_core__pb2.Job:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SubmitJob",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.SubmitJobRequest,
                output=workflows_dot_v1_dot_core__pb2.Job,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_job(
        self,
        request: workflows_dot_v1_dot_job__pb2.GetJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_core__pb2.Job:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJob",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.GetJobRequest,
                output=workflows_dot_v1_dot_core__pb2.Job,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_job_progress(
        self,
        request: workflows_dot_v1_dot_job__pb2.GetJobProgressRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_core__pb2.Job:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJobProgress",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.GetJobProgressRequest,
                output=workflows_dot_v1_dot_core__pb2.Job,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def retry_job(
        self,
        request: workflows_dot_v1_dot_job__pb2.RetryJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_job__pb2.RetryJobResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RetryJob",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.RetryJobRequest,
                output=workflows_dot_v1_dot_job__pb2.RetryJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def cancel_job(
        self,
        request: workflows_dot_v1_dot_job__pb2.CancelJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_job__pb2.CancelJobResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelJob",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.CancelJobRequest,
                output=workflows_dot_v1_dot_job__pb2.CancelJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def visualize_job(
        self,
        request: workflows_dot_v1_dot_job__pb2.VisualizeJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_diagram__pb2.Diagram:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="VisualizeJob",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.VisualizeJobRequest,
                output=workflows_dot_v1_dot_diagram__pb2.Diagram,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def query_jobs(
        self,
        request: workflows_dot_v1_dot_job__pb2.QueryJobsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_job__pb2.QueryJobsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="QueryJobs",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.QueryJobsRequest,
                output=workflows_dot_v1_dot_job__pb2.QueryJobsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_job_prototype(
        self,
        request: workflows_dot_v1_dot_job__pb2.GetJobPrototypeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_job__pb2.GetJobPrototypeResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJobPrototype",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.GetJobPrototypeRequest,
                output=workflows_dot_v1_dot_job__pb2.GetJobPrototypeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def clone_job(
        self,
        request: workflows_dot_v1_dot_job__pb2.CloneJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_core__pb2.Job:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CloneJob",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.CloneJobRequest,
                output=workflows_dot_v1_dot_core__pb2.Job,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class JobServiceSync(Protocol):
    def submit_job(self, request: workflows_dot_v1_dot_job__pb2.SubmitJobRequest, ctx: RequestContext) -> workflows_dot_v1_dot_core__pb2.Job:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_job(self, request: workflows_dot_v1_dot_job__pb2.GetJobRequest, ctx: RequestContext) -> workflows_dot_v1_dot_core__pb2.Job:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_job_progress(self, request: workflows_dot_v1_dot_job__pb2.GetJobProgressRequest, ctx: RequestContext) -> workflows_dot_v1_dot_core__pb2.Job:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def retry_job(self, request: workflows_dot_v1_dot_job__pb2.RetryJobRequest, ctx: RequestContext) -> workflows_dot_v1_dot_job__pb2.RetryJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def cancel_job(self, request: workflows_dot_v1_dot_job__pb2.CancelJobRequest, ctx: RequestContext) -> workflows_dot_v1_dot_job__pb2.CancelJobResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def visualize_job(self, request: workflows_dot_v1_dot_job__pb2.VisualizeJobRequest, ctx: RequestContext) -> workflows_dot_v1_dot_diagram__pb2.Diagram:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def query_jobs(self, request: workflows_dot_v1_dot_job__pb2.QueryJobsRequest, ctx: RequestContext) -> workflows_dot_v1_dot_job__pb2.QueryJobsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_job_prototype(self, request: workflows_dot_v1_dot_job__pb2.GetJobPrototypeRequest, ctx: RequestContext) -> workflows_dot_v1_dot_job__pb2.GetJobPrototypeResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def clone_job(self, request: workflows_dot_v1_dot_job__pb2.CloneJobRequest, ctx: RequestContext) -> workflows_dot_v1_dot_core__pb2.Job:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class JobServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: JobServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/workflows.v1.JobService/SubmitJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="SubmitJob",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.SubmitJobRequest,
                        output=workflows_dot_v1_dot_core__pb2.Job,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.submit_job,
                ),
                "/workflows.v1.JobService/GetJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetJob",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.GetJobRequest,
                        output=workflows_dot_v1_dot_core__pb2.Job,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_job,
                ),
                "/workflows.v1.JobService/GetJobProgress": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetJobProgress",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.GetJobProgressRequest,
                        output=workflows_dot_v1_dot_core__pb2.Job,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_job_progress,
                ),
                "/workflows.v1.JobService/RetryJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="RetryJob",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.RetryJobRequest,
                        output=workflows_dot_v1_dot_job__pb2.RetryJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.retry_job,
                ),
                "/workflows.v1.JobService/CancelJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="CancelJob",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.CancelJobRequest,
                        output=workflows_dot_v1_dot_job__pb2.CancelJobResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.cancel_job,
                ),
                "/workflows.v1.JobService/VisualizeJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="VisualizeJob",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.VisualizeJobRequest,
                        output=workflows_dot_v1_dot_diagram__pb2.Diagram,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.visualize_job,
                ),
                "/workflows.v1.JobService/QueryJobs": EndpointSync.unary(
                    method=MethodInfo(
                        name="QueryJobs",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.QueryJobsRequest,
                        output=workflows_dot_v1_dot_job__pb2.QueryJobsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.query_jobs,
                ),
                "/workflows.v1.JobService/GetJobPrototype": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetJobPrototype",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.GetJobPrototypeRequest,
                        output=workflows_dot_v1_dot_job__pb2.GetJobPrototypeResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_job_prototype,
                ),
                "/workflows.v1.JobService/CloneJob": EndpointSync.unary(
                    method=MethodInfo(
                        name="CloneJob",
                        service_name="workflows.v1.JobService",
                        input=workflows_dot_v1_dot_job__pb2.CloneJobRequest,
                        output=workflows_dot_v1_dot_core__pb2.Job,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.clone_job,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/workflows.v1.JobService"


class JobServiceClientSync(ConnectClientSync):
    def submit_job(
        self,
        request: workflows_dot_v1_dot_job__pb2.SubmitJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_core__pb2.Job:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SubmitJob",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.SubmitJobRequest,
                output=workflows_dot_v1_dot_core__pb2.Job,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_job(
        self,
        request: workflows_dot_v1_dot_job__pb2.GetJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_core__pb2.Job:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJob",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.GetJobRequest,
                output=workflows_dot_v1_dot_core__pb2.Job,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_job_progress(
        self,
        request: workflows_dot_v1_dot_job__pb2.GetJobProgressRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_core__pb2.Job:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJobProgress",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.GetJobProgressRequest,
                output=workflows_dot_v1_dot_core__pb2.Job,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def retry_job(
        self,
        request: workflows_dot_v1_dot_job__pb2.RetryJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_job__pb2.RetryJobResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RetryJob",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.RetryJobRequest,
                output=workflows_dot_v1_dot_job__pb2.RetryJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def cancel_job(
        self,
        request: workflows_dot_v1_dot_job__pb2.CancelJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_job__pb2.CancelJobResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CancelJob",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.CancelJobRequest,
                output=workflows_dot_v1_dot_job__pb2.CancelJobResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def visualize_job(
        self,
        request: workflows_dot_v1_dot_job__pb2.VisualizeJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_diagram__pb2.Diagram:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="VisualizeJob",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.VisualizeJobRequest,
                output=workflows_dot_v1_dot_diagram__pb2.Diagram,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def query_jobs(
        self,
        request: workflows_dot_v1_dot_job__pb2.QueryJobsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_job__pb2.QueryJobsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="QueryJobs",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.QueryJobsRequest,
                output=workflows_dot_v1_dot_job__pb2.QueryJobsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_job_prototype(
        self,
        request: workflows_dot_v1_dot_job__pb2.GetJobPrototypeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_job__pb2.GetJobPrototypeResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetJobPrototype",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.GetJobPrototypeRequest,
                output=workflows_dot_v1_dot_job__pb2.GetJobPrototypeResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def clone_job(
        self,
        request: workflows_dot_v1_dot_job__pb2.CloneJobRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_core__pb2.Job:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CloneJob",
                service_name="workflows.v1.JobService",
                input=workflows_dot_v1_dot_job__pb2.CloneJobRequest,
                output=workflows_dot_v1_dot_core__pb2.Job,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
