# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from tilebox.datasets.tilebox.v1 import id_pb2 as tilebox_dot_v1_dot_id__pb2
from tilebox.workflows.workflows.v1 import storage_location_pb2 as workflows_dot_v1_dot_storage__location__pb2


class StorageLocationServiceStub:
    """StorageLocationService manages storage locations, notification subscriptions, and received events.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListStorageLocations = channel.unary_unary(
                '/workflows.v1.StorageLocationService/ListStorageLocations',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=workflows_dot_v1_dot_storage__location__pb2.StorageLocations.FromString,
                _registered_method=True)
        self.GetStorageLocation = channel.unary_unary(
                '/workflows.v1.StorageLocationService/GetStorageLocation',
                request_serializer=tilebox_dot_v1_dot_id__pb2.ID.SerializeToString,
                response_deserializer=workflows_dot_v1_dot_storage__location__pb2.StorageLocation.FromString,
                _registered_method=True)
        self.CreateStorageLocation = channel.unary_unary(
                '/workflows.v1.StorageLocationService/CreateStorageLocation',
                request_serializer=workflows_dot_v1_dot_storage__location__pb2.CreateStorageLocationRequest.SerializeToString,
                response_deserializer=workflows_dot_v1_dot_storage__location__pb2.StorageLocation.FromString,
                _registered_method=True)
        self.UpdateStorageLocation = channel.unary_unary(
                '/workflows.v1.StorageLocationService/UpdateStorageLocation',
                request_serializer=workflows_dot_v1_dot_storage__location__pb2.UpdateStorageLocationRequest.SerializeToString,
                response_deserializer=workflows_dot_v1_dot_storage__location__pb2.StorageLocation.FromString,
                _registered_method=True)
        self.DeleteStorageLocation = channel.unary_unary(
                '/workflows.v1.StorageLocationService/DeleteStorageLocation',
                request_serializer=tilebox_dot_v1_dot_id__pb2.ID.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateStorageSubscription = channel.unary_unary(
                '/workflows.v1.StorageLocationService/CreateStorageSubscription',
                request_serializer=workflows_dot_v1_dot_storage__location__pb2.CreateStorageSubscriptionRequest.SerializeToString,
                response_deserializer=workflows_dot_v1_dot_storage__location__pb2.StorageSubscription.FromString,
                _registered_method=True)
        self.ListStorageSubscriptions = channel.unary_unary(
                '/workflows.v1.StorageLocationService/ListStorageSubscriptions',
                request_serializer=workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionsRequest.SerializeToString,
                response_deserializer=workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptions.FromString,
                _registered_method=True)
        self.GetStorageSubscription = channel.unary_unary(
                '/workflows.v1.StorageLocationService/GetStorageSubscription',
                request_serializer=tilebox_dot_v1_dot_id__pb2.ID.SerializeToString,
                response_deserializer=workflows_dot_v1_dot_storage__location__pb2.StorageSubscription.FromString,
                _registered_method=True)
        self.DeleteStorageSubscription = channel.unary_unary(
                '/workflows.v1.StorageLocationService/DeleteStorageSubscription',
                request_serializer=tilebox_dot_v1_dot_id__pb2.ID.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListStorageSubscriptionEvents = channel.unary_unary(
                '/workflows.v1.StorageLocationService/ListStorageSubscriptionEvents',
                request_serializer=workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionEventsRequest.SerializeToString,
                response_deserializer=workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptionEvents.FromString,
                _registered_method=True)


class StorageLocationServiceServicer:
    """StorageLocationService manages storage locations, notification subscriptions, and received events.
    """

    def ListStorageLocations(self, request, context):
        """ListStorageLocations lists storage locations available for automation triggers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStorageLocation(self, request, context):
        """GetStorageLocation gets a storage location by its ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStorageLocation(self, request, context):
        """CreateStorageLocation registers an existing bucket, container, or directory for automation triggers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStorageLocation(self, request, context):
        """UpdateStorageLocation changes the display name of a storage location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStorageLocation(self, request, context):
        """DeleteStorageLocation removes the location and its subscriptions from Tilebox without deleting cloud resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStorageSubscription(self, request, context):
        """CreateStorageSubscription registers notification delivery and returns the provider setup values.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStorageSubscriptions(self, request, context):
        """ListStorageSubscriptions lists notification subscriptions for a storage location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStorageSubscription(self, request, context):
        """GetStorageSubscription gets a subscription by its ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStorageSubscription(self, request, context):
        """DeleteStorageSubscription stops accepting notifications at its endpoint without deleting cloud resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStorageSubscriptionEvents(self, request, context):
        """ListStorageSubscriptionEvents lists received object notifications and the jobs they triggered.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageLocationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListStorageLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStorageLocations,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=workflows_dot_v1_dot_storage__location__pb2.StorageLocations.SerializeToString,
            ),
            'GetStorageLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStorageLocation,
                    request_deserializer=tilebox_dot_v1_dot_id__pb2.ID.FromString,
                    response_serializer=workflows_dot_v1_dot_storage__location__pb2.StorageLocation.SerializeToString,
            ),
            'CreateStorageLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStorageLocation,
                    request_deserializer=workflows_dot_v1_dot_storage__location__pb2.CreateStorageLocationRequest.FromString,
                    response_serializer=workflows_dot_v1_dot_storage__location__pb2.StorageLocation.SerializeToString,
            ),
            'UpdateStorageLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStorageLocation,
                    request_deserializer=workflows_dot_v1_dot_storage__location__pb2.UpdateStorageLocationRequest.FromString,
                    response_serializer=workflows_dot_v1_dot_storage__location__pb2.StorageLocation.SerializeToString,
            ),
            'DeleteStorageLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStorageLocation,
                    request_deserializer=tilebox_dot_v1_dot_id__pb2.ID.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateStorageSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStorageSubscription,
                    request_deserializer=workflows_dot_v1_dot_storage__location__pb2.CreateStorageSubscriptionRequest.FromString,
                    response_serializer=workflows_dot_v1_dot_storage__location__pb2.StorageSubscription.SerializeToString,
            ),
            'ListStorageSubscriptions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStorageSubscriptions,
                    request_deserializer=workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionsRequest.FromString,
                    response_serializer=workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptions.SerializeToString,
            ),
            'GetStorageSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStorageSubscription,
                    request_deserializer=tilebox_dot_v1_dot_id__pb2.ID.FromString,
                    response_serializer=workflows_dot_v1_dot_storage__location__pb2.StorageSubscription.SerializeToString,
            ),
            'DeleteStorageSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStorageSubscription,
                    request_deserializer=tilebox_dot_v1_dot_id__pb2.ID.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListStorageSubscriptionEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStorageSubscriptionEvents,
                    request_deserializer=workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionEventsRequest.FromString,
                    response_serializer=workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptionEvents.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workflows.v1.StorageLocationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workflows.v1.StorageLocationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageLocationService:
    """StorageLocationService manages storage locations, notification subscriptions, and received events.
    """

    @staticmethod
    def ListStorageLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.StorageLocationService/ListStorageLocations',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            workflows_dot_v1_dot_storage__location__pb2.StorageLocations.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStorageLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.StorageLocationService/GetStorageLocation',
            tilebox_dot_v1_dot_id__pb2.ID.SerializeToString,
            workflows_dot_v1_dot_storage__location__pb2.StorageLocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateStorageLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.StorageLocationService/CreateStorageLocation',
            workflows_dot_v1_dot_storage__location__pb2.CreateStorageLocationRequest.SerializeToString,
            workflows_dot_v1_dot_storage__location__pb2.StorageLocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStorageLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.StorageLocationService/UpdateStorageLocation',
            workflows_dot_v1_dot_storage__location__pb2.UpdateStorageLocationRequest.SerializeToString,
            workflows_dot_v1_dot_storage__location__pb2.StorageLocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStorageLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.StorageLocationService/DeleteStorageLocation',
            tilebox_dot_v1_dot_id__pb2.ID.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateStorageSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.StorageLocationService/CreateStorageSubscription',
            workflows_dot_v1_dot_storage__location__pb2.CreateStorageSubscriptionRequest.SerializeToString,
            workflows_dot_v1_dot_storage__location__pb2.StorageSubscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStorageSubscriptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.StorageLocationService/ListStorageSubscriptions',
            workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionsRequest.SerializeToString,
            workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptions.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStorageSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.StorageLocationService/GetStorageSubscription',
            tilebox_dot_v1_dot_id__pb2.ID.SerializeToString,
            workflows_dot_v1_dot_storage__location__pb2.StorageSubscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStorageSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.StorageLocationService/DeleteStorageSubscription',
            tilebox_dot_v1_dot_id__pb2.ID.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStorageSubscriptionEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.StorageLocationService/ListStorageSubscriptionEvents',
            workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionEventsRequest.SerializeToString,
            workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptionEvents.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
