# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: workflows/v1/storage_location.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2
import tilebox.datasets.tilebox.v1.id_pb2 as tilebox_dot_v1_dot_id__pb2
import tilebox.workflows.workflows.v1.storage_location_pb2 as workflows_dot_v1_dot_storage__location__pb2


class StorageLocationService(Protocol):
    async def list_storage_locations(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocations:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_storage_location(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_storage_location(self, request: workflows_dot_v1_dot_storage__location__pb2.CreateStorageLocationRequest, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_storage_location(self, request: workflows_dot_v1_dot_storage__location__pb2.UpdateStorageLocationRequest, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_storage_location(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_storage_subscription(self, request: workflows_dot_v1_dot_storage__location__pb2.CreateStorageSubscriptionRequest, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscription:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_storage_subscriptions(self, request: workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionsRequest, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptions:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_storage_subscription(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscription:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_storage_subscription(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_storage_subscription_events(self, request: workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionEventsRequest, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptionEvents:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class StorageLocationServiceASGIApplication(ConnectASGIApplication[StorageLocationService]):
    def __init__(self, service: StorageLocationService | AsyncGenerator[StorageLocationService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/workflows.v1.StorageLocationService/ListStorageLocations": Endpoint.unary(
                    method=MethodInfo(
                        name="ListStorageLocations",
                        service_name="workflows.v1.StorageLocationService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageLocations,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_storage_locations,
                ),
                "/workflows.v1.StorageLocationService/GetStorageLocation": Endpoint.unary(
                    method=MethodInfo(
                        name="GetStorageLocation",
                        service_name="workflows.v1.StorageLocationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageLocation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_storage_location,
                ),
                "/workflows.v1.StorageLocationService/CreateStorageLocation": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateStorageLocation",
                        service_name="workflows.v1.StorageLocationService",
                        input=workflows_dot_v1_dot_storage__location__pb2.CreateStorageLocationRequest,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageLocation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_storage_location,
                ),
                "/workflows.v1.StorageLocationService/UpdateStorageLocation": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateStorageLocation",
                        service_name="workflows.v1.StorageLocationService",
                        input=workflows_dot_v1_dot_storage__location__pb2.UpdateStorageLocationRequest,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageLocation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_storage_location,
                ),
                "/workflows.v1.StorageLocationService/DeleteStorageLocation": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteStorageLocation",
                        service_name="workflows.v1.StorageLocationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_storage_location,
                ),
                "/workflows.v1.StorageLocationService/CreateStorageSubscription": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateStorageSubscription",
                        service_name="workflows.v1.StorageLocationService",
                        input=workflows_dot_v1_dot_storage__location__pb2.CreateStorageSubscriptionRequest,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscription,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_storage_subscription,
                ),
                "/workflows.v1.StorageLocationService/ListStorageSubscriptions": Endpoint.unary(
                    method=MethodInfo(
                        name="ListStorageSubscriptions",
                        service_name="workflows.v1.StorageLocationService",
                        input=workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionsRequest,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptions,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_storage_subscriptions,
                ),
                "/workflows.v1.StorageLocationService/GetStorageSubscription": Endpoint.unary(
                    method=MethodInfo(
                        name="GetStorageSubscription",
                        service_name="workflows.v1.StorageLocationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscription,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_storage_subscription,
                ),
                "/workflows.v1.StorageLocationService/DeleteStorageSubscription": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteStorageSubscription",
                        service_name="workflows.v1.StorageLocationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_storage_subscription,
                ),
                "/workflows.v1.StorageLocationService/ListStorageSubscriptionEvents": Endpoint.unary(
                    method=MethodInfo(
                        name="ListStorageSubscriptionEvents",
                        service_name="workflows.v1.StorageLocationService",
                        input=workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionEventsRequest,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptionEvents,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_storage_subscription_events,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/workflows.v1.StorageLocationService"


class StorageLocationServiceClient(ConnectClient):
    async def list_storage_locations(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocations:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStorageLocations",
                service_name="workflows.v1.StorageLocationService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageLocations,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_storage_location(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocation:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStorageLocation",
                service_name="workflows.v1.StorageLocationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageLocation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_storage_location(
        self,
        request: workflows_dot_v1_dot_storage__location__pb2.CreateStorageLocationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocation:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateStorageLocation",
                service_name="workflows.v1.StorageLocationService",
                input=workflows_dot_v1_dot_storage__location__pb2.CreateStorageLocationRequest,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageLocation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_storage_location(
        self,
        request: workflows_dot_v1_dot_storage__location__pb2.UpdateStorageLocationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocation:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateStorageLocation",
                service_name="workflows.v1.StorageLocationService",
                input=workflows_dot_v1_dot_storage__location__pb2.UpdateStorageLocationRequest,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageLocation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_storage_location(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteStorageLocation",
                service_name="workflows.v1.StorageLocationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_storage_subscription(
        self,
        request: workflows_dot_v1_dot_storage__location__pb2.CreateStorageSubscriptionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscription:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateStorageSubscription",
                service_name="workflows.v1.StorageLocationService",
                input=workflows_dot_v1_dot_storage__location__pb2.CreateStorageSubscriptionRequest,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscription,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_storage_subscriptions(
        self,
        request: workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptions:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStorageSubscriptions",
                service_name="workflows.v1.StorageLocationService",
                input=workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionsRequest,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptions,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_storage_subscription(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscription:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStorageSubscription",
                service_name="workflows.v1.StorageLocationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscription,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_storage_subscription(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteStorageSubscription",
                service_name="workflows.v1.StorageLocationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_storage_subscription_events(
        self,
        request: workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptionEvents:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStorageSubscriptionEvents",
                service_name="workflows.v1.StorageLocationService",
                input=workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionEventsRequest,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptionEvents,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class StorageLocationServiceSync(Protocol):
    def list_storage_locations(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocations:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_storage_location(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_storage_location(self, request: workflows_dot_v1_dot_storage__location__pb2.CreateStorageLocationRequest, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_storage_location(self, request: workflows_dot_v1_dot_storage__location__pb2.UpdateStorageLocationRequest, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_storage_location(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_storage_subscription(self, request: workflows_dot_v1_dot_storage__location__pb2.CreateStorageSubscriptionRequest, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscription:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_storage_subscriptions(self, request: workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionsRequest, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptions:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_storage_subscription(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscription:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_storage_subscription(self, request: tilebox_dot_v1_dot_id__pb2.ID, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_storage_subscription_events(self, request: workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionEventsRequest, ctx: RequestContext) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptionEvents:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class StorageLocationServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: StorageLocationServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/workflows.v1.StorageLocationService/ListStorageLocations": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListStorageLocations",
                        service_name="workflows.v1.StorageLocationService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageLocations,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_storage_locations,
                ),
                "/workflows.v1.StorageLocationService/GetStorageLocation": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetStorageLocation",
                        service_name="workflows.v1.StorageLocationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageLocation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_storage_location,
                ),
                "/workflows.v1.StorageLocationService/CreateStorageLocation": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateStorageLocation",
                        service_name="workflows.v1.StorageLocationService",
                        input=workflows_dot_v1_dot_storage__location__pb2.CreateStorageLocationRequest,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageLocation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_storage_location,
                ),
                "/workflows.v1.StorageLocationService/UpdateStorageLocation": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateStorageLocation",
                        service_name="workflows.v1.StorageLocationService",
                        input=workflows_dot_v1_dot_storage__location__pb2.UpdateStorageLocationRequest,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageLocation,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_storage_location,
                ),
                "/workflows.v1.StorageLocationService/DeleteStorageLocation": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteStorageLocation",
                        service_name="workflows.v1.StorageLocationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_storage_location,
                ),
                "/workflows.v1.StorageLocationService/CreateStorageSubscription": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateStorageSubscription",
                        service_name="workflows.v1.StorageLocationService",
                        input=workflows_dot_v1_dot_storage__location__pb2.CreateStorageSubscriptionRequest,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscription,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_storage_subscription,
                ),
                "/workflows.v1.StorageLocationService/ListStorageSubscriptions": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListStorageSubscriptions",
                        service_name="workflows.v1.StorageLocationService",
                        input=workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionsRequest,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptions,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_storage_subscriptions,
                ),
                "/workflows.v1.StorageLocationService/GetStorageSubscription": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetStorageSubscription",
                        service_name="workflows.v1.StorageLocationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscription,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_storage_subscription,
                ),
                "/workflows.v1.StorageLocationService/DeleteStorageSubscription": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteStorageSubscription",
                        service_name="workflows.v1.StorageLocationService",
                        input=tilebox_dot_v1_dot_id__pb2.ID,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_storage_subscription,
                ),
                "/workflows.v1.StorageLocationService/ListStorageSubscriptionEvents": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListStorageSubscriptionEvents",
                        service_name="workflows.v1.StorageLocationService",
                        input=workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionEventsRequest,
                        output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptionEvents,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_storage_subscription_events,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/workflows.v1.StorageLocationService"


class StorageLocationServiceClientSync(ConnectClientSync):
    def list_storage_locations(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocations:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStorageLocations",
                service_name="workflows.v1.StorageLocationService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageLocations,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_storage_location(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocation:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStorageLocation",
                service_name="workflows.v1.StorageLocationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageLocation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_storage_location(
        self,
        request: workflows_dot_v1_dot_storage__location__pb2.CreateStorageLocationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocation:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateStorageLocation",
                service_name="workflows.v1.StorageLocationService",
                input=workflows_dot_v1_dot_storage__location__pb2.CreateStorageLocationRequest,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageLocation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_storage_location(
        self,
        request: workflows_dot_v1_dot_storage__location__pb2.UpdateStorageLocationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageLocation:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateStorageLocation",
                service_name="workflows.v1.StorageLocationService",
                input=workflows_dot_v1_dot_storage__location__pb2.UpdateStorageLocationRequest,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageLocation,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_storage_location(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteStorageLocation",
                service_name="workflows.v1.StorageLocationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_storage_subscription(
        self,
        request: workflows_dot_v1_dot_storage__location__pb2.CreateStorageSubscriptionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscription:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateStorageSubscription",
                service_name="workflows.v1.StorageLocationService",
                input=workflows_dot_v1_dot_storage__location__pb2.CreateStorageSubscriptionRequest,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscription,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_storage_subscriptions(
        self,
        request: workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptions:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStorageSubscriptions",
                service_name="workflows.v1.StorageLocationService",
                input=workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionsRequest,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptions,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_storage_subscription(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscription:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetStorageSubscription",
                service_name="workflows.v1.StorageLocationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscription,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_storage_subscription(
        self,
        request: tilebox_dot_v1_dot_id__pb2.ID,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteStorageSubscription",
                service_name="workflows.v1.StorageLocationService",
                input=tilebox_dot_v1_dot_id__pb2.ID,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_storage_subscription_events(
        self,
        request: workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionEventsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptionEvents:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListStorageSubscriptionEvents",
                service_name="workflows.v1.StorageLocationService",
                input=workflows_dot_v1_dot_storage__location__pb2.ListStorageSubscriptionEventsRequest,
                output=workflows_dot_v1_dot_storage__location__pb2.StorageSubscriptionEvents,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
