# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tilebox.workflows.workflows.v1 import task_release_pb2 as workflows_dot_v1_dot_task__release__pb2


class TaskReleaseServiceStub(object):
    """A service for managing workflows.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishRelease = channel.unary_unary(
                '/workflows.v1.TaskReleaseService/PublishRelease',
                request_serializer=workflows_dot_v1_dot_task__release__pb2.PublishReleaseRequest.SerializeToString,
                response_deserializer=workflows_dot_v1_dot_task__release__pb2.PublishReleaseResponse.FromString,
                _registered_method=True)
        self.DeployRelease = channel.unary_unary(
                '/workflows.v1.TaskReleaseService/DeployRelease',
                request_serializer=workflows_dot_v1_dot_task__release__pb2.DeployReleaseRequest.SerializeToString,
                response_deserializer=workflows_dot_v1_dot_task__release__pb2.DeployReleaseResponse.FromString,
                _registered_method=True)
        self.GetClusterDeploymentManifest = channel.unary_unary(
                '/workflows.v1.TaskReleaseService/GetClusterDeploymentManifest',
                request_serializer=workflows_dot_v1_dot_task__release__pb2.GetClusterDeploymentManifestRequest.SerializeToString,
                response_deserializer=workflows_dot_v1_dot_task__release__pb2.GetClusterDeploymentManifestResponse.FromString,
                _registered_method=True)


class TaskReleaseServiceServicer(object):
    """A service for managing workflows.
    """

    def PublishRelease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployRelease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterDeploymentManifest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskReleaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishRelease': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishRelease,
                    request_deserializer=workflows_dot_v1_dot_task__release__pb2.PublishReleaseRequest.FromString,
                    response_serializer=workflows_dot_v1_dot_task__release__pb2.PublishReleaseResponse.SerializeToString,
            ),
            'DeployRelease': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployRelease,
                    request_deserializer=workflows_dot_v1_dot_task__release__pb2.DeployReleaseRequest.FromString,
                    response_serializer=workflows_dot_v1_dot_task__release__pb2.DeployReleaseResponse.SerializeToString,
            ),
            'GetClusterDeploymentManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterDeploymentManifest,
                    request_deserializer=workflows_dot_v1_dot_task__release__pb2.GetClusterDeploymentManifestRequest.FromString,
                    response_serializer=workflows_dot_v1_dot_task__release__pb2.GetClusterDeploymentManifestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workflows.v1.TaskReleaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workflows.v1.TaskReleaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskReleaseService(object):
    """A service for managing workflows.
    """

    @staticmethod
    def PublishRelease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.TaskReleaseService/PublishRelease',
            workflows_dot_v1_dot_task__release__pb2.PublishReleaseRequest.SerializeToString,
            workflows_dot_v1_dot_task__release__pb2.PublishReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployRelease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.TaskReleaseService/DeployRelease',
            workflows_dot_v1_dot_task__release__pb2.DeployReleaseRequest.SerializeToString,
            workflows_dot_v1_dot_task__release__pb2.DeployReleaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterDeploymentManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflows.v1.TaskReleaseService/GetClusterDeploymentManifest',
            workflows_dot_v1_dot_task__release__pb2.GetClusterDeploymentManifestRequest.SerializeToString,
            workflows_dot_v1_dot_task__release__pb2.GetClusterDeploymentManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
