# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: workflows/v1/telemetry.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import tilebox.workflows.workflows.v1.telemetry_pb2 as workflows_dot_v1_dot_telemetry__pb2


class TelemetryQueryService(Protocol):
    async def query_job_logs(self, request: workflows_dot_v1_dot_telemetry__pb2.QueryJobLogsRequest, ctx: RequestContext) -> workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def query_logs_in_interval(self, request: workflows_dot_v1_dot_telemetry__pb2.QueryLogsInIntervalRequest, ctx: RequestContext) -> workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def query_job_spans(self, request: workflows_dot_v1_dot_telemetry__pb2.QueryJobSpansRequest, ctx: RequestContext) -> workflows_dot_v1_dot_telemetry__pb2.PaginatedSpansData:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class TelemetryQueryServiceASGIApplication(ConnectASGIApplication[TelemetryQueryService]):
    def __init__(self, service: TelemetryQueryService | AsyncGenerator[TelemetryQueryService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/workflows.v1.TelemetryQueryService/QueryJobLogs": Endpoint.unary(
                    method=MethodInfo(
                        name="QueryJobLogs",
                        service_name="workflows.v1.TelemetryQueryService",
                        input=workflows_dot_v1_dot_telemetry__pb2.QueryJobLogsRequest,
                        output=workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.query_job_logs,
                ),
                "/workflows.v1.TelemetryQueryService/QueryLogsInInterval": Endpoint.unary(
                    method=MethodInfo(
                        name="QueryLogsInInterval",
                        service_name="workflows.v1.TelemetryQueryService",
                        input=workflows_dot_v1_dot_telemetry__pb2.QueryLogsInIntervalRequest,
                        output=workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.query_logs_in_interval,
                ),
                "/workflows.v1.TelemetryQueryService/QueryJobSpans": Endpoint.unary(
                    method=MethodInfo(
                        name="QueryJobSpans",
                        service_name="workflows.v1.TelemetryQueryService",
                        input=workflows_dot_v1_dot_telemetry__pb2.QueryJobSpansRequest,
                        output=workflows_dot_v1_dot_telemetry__pb2.PaginatedSpansData,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.query_job_spans,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/workflows.v1.TelemetryQueryService"


class TelemetryQueryServiceClient(ConnectClient):
    async def query_job_logs(
        self,
        request: workflows_dot_v1_dot_telemetry__pb2.QueryJobLogsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="QueryJobLogs",
                service_name="workflows.v1.TelemetryQueryService",
                input=workflows_dot_v1_dot_telemetry__pb2.QueryJobLogsRequest,
                output=workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def query_logs_in_interval(
        self,
        request: workflows_dot_v1_dot_telemetry__pb2.QueryLogsInIntervalRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="QueryLogsInInterval",
                service_name="workflows.v1.TelemetryQueryService",
                input=workflows_dot_v1_dot_telemetry__pb2.QueryLogsInIntervalRequest,
                output=workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def query_job_spans(
        self,
        request: workflows_dot_v1_dot_telemetry__pb2.QueryJobSpansRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_telemetry__pb2.PaginatedSpansData:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="QueryJobSpans",
                service_name="workflows.v1.TelemetryQueryService",
                input=workflows_dot_v1_dot_telemetry__pb2.QueryJobSpansRequest,
                output=workflows_dot_v1_dot_telemetry__pb2.PaginatedSpansData,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class TelemetryQueryServiceSync(Protocol):
    def query_job_logs(self, request: workflows_dot_v1_dot_telemetry__pb2.QueryJobLogsRequest, ctx: RequestContext) -> workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def query_logs_in_interval(self, request: workflows_dot_v1_dot_telemetry__pb2.QueryLogsInIntervalRequest, ctx: RequestContext) -> workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def query_job_spans(self, request: workflows_dot_v1_dot_telemetry__pb2.QueryJobSpansRequest, ctx: RequestContext) -> workflows_dot_v1_dot_telemetry__pb2.PaginatedSpansData:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class TelemetryQueryServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: TelemetryQueryServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/workflows.v1.TelemetryQueryService/QueryJobLogs": EndpointSync.unary(
                    method=MethodInfo(
                        name="QueryJobLogs",
                        service_name="workflows.v1.TelemetryQueryService",
                        input=workflows_dot_v1_dot_telemetry__pb2.QueryJobLogsRequest,
                        output=workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.query_job_logs,
                ),
                "/workflows.v1.TelemetryQueryService/QueryLogsInInterval": EndpointSync.unary(
                    method=MethodInfo(
                        name="QueryLogsInInterval",
                        service_name="workflows.v1.TelemetryQueryService",
                        input=workflows_dot_v1_dot_telemetry__pb2.QueryLogsInIntervalRequest,
                        output=workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.query_logs_in_interval,
                ),
                "/workflows.v1.TelemetryQueryService/QueryJobSpans": EndpointSync.unary(
                    method=MethodInfo(
                        name="QueryJobSpans",
                        service_name="workflows.v1.TelemetryQueryService",
                        input=workflows_dot_v1_dot_telemetry__pb2.QueryJobSpansRequest,
                        output=workflows_dot_v1_dot_telemetry__pb2.PaginatedSpansData,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.query_job_spans,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/workflows.v1.TelemetryQueryService"


class TelemetryQueryServiceClientSync(ConnectClientSync):
    def query_job_logs(
        self,
        request: workflows_dot_v1_dot_telemetry__pb2.QueryJobLogsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="QueryJobLogs",
                service_name="workflows.v1.TelemetryQueryService",
                input=workflows_dot_v1_dot_telemetry__pb2.QueryJobLogsRequest,
                output=workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def query_logs_in_interval(
        self,
        request: workflows_dot_v1_dot_telemetry__pb2.QueryLogsInIntervalRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="QueryLogsInInterval",
                service_name="workflows.v1.TelemetryQueryService",
                input=workflows_dot_v1_dot_telemetry__pb2.QueryLogsInIntervalRequest,
                output=workflows_dot_v1_dot_telemetry__pb2.PaginatedLogsData,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def query_job_spans(
        self,
        request: workflows_dot_v1_dot_telemetry__pb2.QueryJobSpansRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_telemetry__pb2.PaginatedSpansData:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="QueryJobSpans",
                service_name="workflows.v1.TelemetryQueryService",
                input=workflows_dot_v1_dot_telemetry__pb2.QueryJobSpansRequest,
                output=workflows_dot_v1_dot_telemetry__pb2.PaginatedSpansData,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
