# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: workflows/v1/workflows.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import tilebox.workflows.workflows.v1.workflows_pb2 as workflows_dot_v1_dot_workflows__pb2


class WorkflowsService(Protocol):
    async def create_cluster(self, request: workflows_dot_v1_dot_workflows__pb2.CreateClusterRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.Cluster:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_cluster(self, request: workflows_dot_v1_dot_workflows__pb2.GetClusterRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.Cluster:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_cluster(self, request: workflows_dot_v1_dot_workflows__pb2.UpdateClusterRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.Cluster:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_cluster(self, request: workflows_dot_v1_dot_workflows__pb2.DeleteClusterRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.DeleteClusterResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_clusters(self, request: workflows_dot_v1_dot_workflows__pb2.ListClustersRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.ListClustersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_workflow(self, request: workflows_dot_v1_dot_workflows__pb2.CreateWorkflowRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.Workflow:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_workflows(self, request: workflows_dot_v1_dot_workflows__pb2.ListWorkflowsRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.ListWorkflowsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_workflow(self, request: workflows_dot_v1_dot_workflows__pb2.GetWorkflowRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.Workflow:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_workflow(self, request: workflows_dot_v1_dot_workflows__pb2.UpdateWorkflowRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.Workflow:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_workflow(self, request: workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def publish_workflow_release(self, request: workflows_dot_v1_dot_workflows__pb2.PublishWorkflowReleaseRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.WorkflowRelease:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def unpublish_workflow_release(self, request: workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def deploy_workflow_release(self, request: workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def undeploy_workflow_release(self, request: workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class WorkflowsServiceASGIApplication(ConnectASGIApplication[WorkflowsService]):
    def __init__(self, service: WorkflowsService | AsyncGenerator[WorkflowsService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/workflows.v1.WorkflowsService/CreateCluster": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateCluster",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.CreateClusterRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.Cluster,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_cluster,
                ),
                "/workflows.v1.WorkflowsService/GetCluster": Endpoint.unary(
                    method=MethodInfo(
                        name="GetCluster",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.GetClusterRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.Cluster,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_cluster,
                ),
                "/workflows.v1.WorkflowsService/UpdateCluster": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateCluster",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.UpdateClusterRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.Cluster,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_cluster,
                ),
                "/workflows.v1.WorkflowsService/DeleteCluster": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteCluster",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.DeleteClusterRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.DeleteClusterResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_cluster,
                ),
                "/workflows.v1.WorkflowsService/ListClusters": Endpoint.unary(
                    method=MethodInfo(
                        name="ListClusters",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.ListClustersRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.ListClustersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_clusters,
                ),
                "/workflows.v1.WorkflowsService/CreateWorkflow": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateWorkflow",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.CreateWorkflowRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.Workflow,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_workflow,
                ),
                "/workflows.v1.WorkflowsService/ListWorkflows": Endpoint.unary(
                    method=MethodInfo(
                        name="ListWorkflows",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.ListWorkflowsRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.ListWorkflowsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_workflows,
                ),
                "/workflows.v1.WorkflowsService/GetWorkflow": Endpoint.unary(
                    method=MethodInfo(
                        name="GetWorkflow",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.GetWorkflowRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.Workflow,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_workflow,
                ),
                "/workflows.v1.WorkflowsService/UpdateWorkflow": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateWorkflow",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.UpdateWorkflowRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.Workflow,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_workflow,
                ),
                "/workflows.v1.WorkflowsService/DeleteWorkflow": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteWorkflow",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_workflow,
                ),
                "/workflows.v1.WorkflowsService/PublishWorkflowRelease": Endpoint.unary(
                    method=MethodInfo(
                        name="PublishWorkflowRelease",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.PublishWorkflowReleaseRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.WorkflowRelease,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.publish_workflow_release,
                ),
                "/workflows.v1.WorkflowsService/UnpublishWorkflowRelease": Endpoint.unary(
                    method=MethodInfo(
                        name="UnpublishWorkflowRelease",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.unpublish_workflow_release,
                ),
                "/workflows.v1.WorkflowsService/DeployWorkflowRelease": Endpoint.unary(
                    method=MethodInfo(
                        name="DeployWorkflowRelease",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.deploy_workflow_release,
                ),
                "/workflows.v1.WorkflowsService/UndeployWorkflowRelease": Endpoint.unary(
                    method=MethodInfo(
                        name="UndeployWorkflowRelease",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.undeploy_workflow_release,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/workflows.v1.WorkflowsService"


class WorkflowsServiceClient(ConnectClient):
    async def create_cluster(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.CreateClusterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.Cluster:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateCluster",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.CreateClusterRequest,
                output=workflows_dot_v1_dot_workflows__pb2.Cluster,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_cluster(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.GetClusterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.Cluster:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCluster",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.GetClusterRequest,
                output=workflows_dot_v1_dot_workflows__pb2.Cluster,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_cluster(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.UpdateClusterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.Cluster:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateCluster",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.UpdateClusterRequest,
                output=workflows_dot_v1_dot_workflows__pb2.Cluster,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_cluster(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.DeleteClusterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.DeleteClusterResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteCluster",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.DeleteClusterRequest,
                output=workflows_dot_v1_dot_workflows__pb2.DeleteClusterResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_clusters(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.ListClustersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.ListClustersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListClusters",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.ListClustersRequest,
                output=workflows_dot_v1_dot_workflows__pb2.ListClustersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_workflow(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.CreateWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.Workflow:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateWorkflow",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.CreateWorkflowRequest,
                output=workflows_dot_v1_dot_workflows__pb2.Workflow,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_workflows(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.ListWorkflowsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.ListWorkflowsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListWorkflows",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.ListWorkflowsRequest,
                output=workflows_dot_v1_dot_workflows__pb2.ListWorkflowsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_workflow(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.GetWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.Workflow:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetWorkflow",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.GetWorkflowRequest,
                output=workflows_dot_v1_dot_workflows__pb2.Workflow,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_workflow(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.UpdateWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.Workflow:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateWorkflow",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.UpdateWorkflowRequest,
                output=workflows_dot_v1_dot_workflows__pb2.Workflow,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_workflow(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteWorkflow",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowRequest,
                output=workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def publish_workflow_release(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.PublishWorkflowReleaseRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.WorkflowRelease:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PublishWorkflowRelease",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.PublishWorkflowReleaseRequest,
                output=workflows_dot_v1_dot_workflows__pb2.WorkflowRelease,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def unpublish_workflow_release(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnpublishWorkflowRelease",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseRequest,
                output=workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def deploy_workflow_release(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeployWorkflowRelease",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseRequest,
                output=workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def undeploy_workflow_release(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UndeployWorkflowRelease",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseRequest,
                output=workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class WorkflowsServiceSync(Protocol):
    def create_cluster(self, request: workflows_dot_v1_dot_workflows__pb2.CreateClusterRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.Cluster:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_cluster(self, request: workflows_dot_v1_dot_workflows__pb2.GetClusterRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.Cluster:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_cluster(self, request: workflows_dot_v1_dot_workflows__pb2.UpdateClusterRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.Cluster:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_cluster(self, request: workflows_dot_v1_dot_workflows__pb2.DeleteClusterRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.DeleteClusterResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_clusters(self, request: workflows_dot_v1_dot_workflows__pb2.ListClustersRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.ListClustersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_workflow(self, request: workflows_dot_v1_dot_workflows__pb2.CreateWorkflowRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.Workflow:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_workflows(self, request: workflows_dot_v1_dot_workflows__pb2.ListWorkflowsRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.ListWorkflowsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_workflow(self, request: workflows_dot_v1_dot_workflows__pb2.GetWorkflowRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.Workflow:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_workflow(self, request: workflows_dot_v1_dot_workflows__pb2.UpdateWorkflowRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.Workflow:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_workflow(self, request: workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def publish_workflow_release(self, request: workflows_dot_v1_dot_workflows__pb2.PublishWorkflowReleaseRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.WorkflowRelease:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def unpublish_workflow_release(self, request: workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def deploy_workflow_release(self, request: workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def undeploy_workflow_release(self, request: workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseRequest, ctx: RequestContext) -> workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class WorkflowsServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: WorkflowsServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/workflows.v1.WorkflowsService/CreateCluster": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateCluster",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.CreateClusterRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.Cluster,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_cluster,
                ),
                "/workflows.v1.WorkflowsService/GetCluster": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetCluster",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.GetClusterRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.Cluster,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_cluster,
                ),
                "/workflows.v1.WorkflowsService/UpdateCluster": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateCluster",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.UpdateClusterRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.Cluster,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_cluster,
                ),
                "/workflows.v1.WorkflowsService/DeleteCluster": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteCluster",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.DeleteClusterRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.DeleteClusterResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_cluster,
                ),
                "/workflows.v1.WorkflowsService/ListClusters": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListClusters",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.ListClustersRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.ListClustersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_clusters,
                ),
                "/workflows.v1.WorkflowsService/CreateWorkflow": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateWorkflow",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.CreateWorkflowRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.Workflow,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_workflow,
                ),
                "/workflows.v1.WorkflowsService/ListWorkflows": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListWorkflows",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.ListWorkflowsRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.ListWorkflowsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_workflows,
                ),
                "/workflows.v1.WorkflowsService/GetWorkflow": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetWorkflow",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.GetWorkflowRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.Workflow,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_workflow,
                ),
                "/workflows.v1.WorkflowsService/UpdateWorkflow": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateWorkflow",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.UpdateWorkflowRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.Workflow,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_workflow,
                ),
                "/workflows.v1.WorkflowsService/DeleteWorkflow": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteWorkflow",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_workflow,
                ),
                "/workflows.v1.WorkflowsService/PublishWorkflowRelease": EndpointSync.unary(
                    method=MethodInfo(
                        name="PublishWorkflowRelease",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.PublishWorkflowReleaseRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.WorkflowRelease,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.publish_workflow_release,
                ),
                "/workflows.v1.WorkflowsService/UnpublishWorkflowRelease": EndpointSync.unary(
                    method=MethodInfo(
                        name="UnpublishWorkflowRelease",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.unpublish_workflow_release,
                ),
                "/workflows.v1.WorkflowsService/DeployWorkflowRelease": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeployWorkflowRelease",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.deploy_workflow_release,
                ),
                "/workflows.v1.WorkflowsService/UndeployWorkflowRelease": EndpointSync.unary(
                    method=MethodInfo(
                        name="UndeployWorkflowRelease",
                        service_name="workflows.v1.WorkflowsService",
                        input=workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseRequest,
                        output=workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.undeploy_workflow_release,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/workflows.v1.WorkflowsService"


class WorkflowsServiceClientSync(ConnectClientSync):
    def create_cluster(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.CreateClusterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.Cluster:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateCluster",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.CreateClusterRequest,
                output=workflows_dot_v1_dot_workflows__pb2.Cluster,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_cluster(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.GetClusterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.Cluster:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCluster",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.GetClusterRequest,
                output=workflows_dot_v1_dot_workflows__pb2.Cluster,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_cluster(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.UpdateClusterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.Cluster:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateCluster",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.UpdateClusterRequest,
                output=workflows_dot_v1_dot_workflows__pb2.Cluster,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_cluster(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.DeleteClusterRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.DeleteClusterResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteCluster",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.DeleteClusterRequest,
                output=workflows_dot_v1_dot_workflows__pb2.DeleteClusterResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_clusters(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.ListClustersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.ListClustersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListClusters",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.ListClustersRequest,
                output=workflows_dot_v1_dot_workflows__pb2.ListClustersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_workflow(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.CreateWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.Workflow:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateWorkflow",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.CreateWorkflowRequest,
                output=workflows_dot_v1_dot_workflows__pb2.Workflow,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_workflows(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.ListWorkflowsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.ListWorkflowsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListWorkflows",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.ListWorkflowsRequest,
                output=workflows_dot_v1_dot_workflows__pb2.ListWorkflowsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_workflow(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.GetWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.Workflow:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetWorkflow",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.GetWorkflowRequest,
                output=workflows_dot_v1_dot_workflows__pb2.Workflow,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_workflow(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.UpdateWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.Workflow:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateWorkflow",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.UpdateWorkflowRequest,
                output=workflows_dot_v1_dot_workflows__pb2.Workflow,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_workflow(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteWorkflow",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowRequest,
                output=workflows_dot_v1_dot_workflows__pb2.DeleteWorkflowResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def publish_workflow_release(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.PublishWorkflowReleaseRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.WorkflowRelease:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PublishWorkflowRelease",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.PublishWorkflowReleaseRequest,
                output=workflows_dot_v1_dot_workflows__pb2.WorkflowRelease,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def unpublish_workflow_release(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UnpublishWorkflowRelease",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseRequest,
                output=workflows_dot_v1_dot_workflows__pb2.UnpublishWorkflowReleaseResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def deploy_workflow_release(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeployWorkflowRelease",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseRequest,
                output=workflows_dot_v1_dot_workflows__pb2.DeployWorkflowReleaseResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def undeploy_workflow_release(
        self,
        request: workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UndeployWorkflowRelease",
                service_name="workflows.v1.WorkflowsService",
                input=workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseRequest,
                output=workflows_dot_v1_dot_workflows__pb2.UndeployWorkflowReleaseResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
