# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: workflows/v1/worker.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2
import tilebox.workflows.workflows.v1.core_pb2 as workflows_dot_v1_dot_core__pb2
import tilebox.workflows.workflows.v1.worker_pb2 as workflows_dot_v1_dot_worker__pb2


class WorkerService(Protocol):
    async def list_registered_tasks(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> workflows_dot_v1_dot_core__pb2.TaskIdentifiers:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def initialize_worker(self, request: workflows_dot_v1_dot_worker__pb2.InitializeRunnerRequest, ctx: RequestContext) -> workflows_dot_v1_dot_worker__pb2.InitializeRunnerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def execute_task(self, request: workflows_dot_v1_dot_core__pb2.Task, ctx: RequestContext) -> workflows_dot_v1_dot_worker__pb2.ExecuteTaskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def shutdown_worker(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class WorkerServiceASGIApplication(ConnectASGIApplication[WorkerService]):
    def __init__(self, service: WorkerService | AsyncGenerator[WorkerService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/workflows.v1.WorkerService/ListRegisteredTasks": Endpoint.unary(
                    method=MethodInfo(
                        name="ListRegisteredTasks",
                        service_name="workflows.v1.WorkerService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=workflows_dot_v1_dot_core__pb2.TaskIdentifiers,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_registered_tasks,
                ),
                "/workflows.v1.WorkerService/InitializeWorker": Endpoint.unary(
                    method=MethodInfo(
                        name="InitializeWorker",
                        service_name="workflows.v1.WorkerService",
                        input=workflows_dot_v1_dot_worker__pb2.InitializeRunnerRequest,
                        output=workflows_dot_v1_dot_worker__pb2.InitializeRunnerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.initialize_worker,
                ),
                "/workflows.v1.WorkerService/ExecuteTask": Endpoint.unary(
                    method=MethodInfo(
                        name="ExecuteTask",
                        service_name="workflows.v1.WorkerService",
                        input=workflows_dot_v1_dot_core__pb2.Task,
                        output=workflows_dot_v1_dot_worker__pb2.ExecuteTaskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.execute_task,
                ),
                "/workflows.v1.WorkerService/ShutdownWorker": Endpoint.unary(
                    method=MethodInfo(
                        name="ShutdownWorker",
                        service_name="workflows.v1.WorkerService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.shutdown_worker,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/workflows.v1.WorkerService"


class WorkerServiceClient(ConnectClient):
    async def list_registered_tasks(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_core__pb2.TaskIdentifiers:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRegisteredTasks",
                service_name="workflows.v1.WorkerService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=workflows_dot_v1_dot_core__pb2.TaskIdentifiers,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def initialize_worker(
        self,
        request: workflows_dot_v1_dot_worker__pb2.InitializeRunnerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_worker__pb2.InitializeRunnerResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="InitializeWorker",
                service_name="workflows.v1.WorkerService",
                input=workflows_dot_v1_dot_worker__pb2.InitializeRunnerRequest,
                output=workflows_dot_v1_dot_worker__pb2.InitializeRunnerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def execute_task(
        self,
        request: workflows_dot_v1_dot_core__pb2.Task,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_worker__pb2.ExecuteTaskResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExecuteTask",
                service_name="workflows.v1.WorkerService",
                input=workflows_dot_v1_dot_core__pb2.Task,
                output=workflows_dot_v1_dot_worker__pb2.ExecuteTaskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def shutdown_worker(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ShutdownWorker",
                service_name="workflows.v1.WorkerService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class WorkerServiceSync(Protocol):
    def list_registered_tasks(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> workflows_dot_v1_dot_core__pb2.TaskIdentifiers:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def initialize_worker(self, request: workflows_dot_v1_dot_worker__pb2.InitializeRunnerRequest, ctx: RequestContext) -> workflows_dot_v1_dot_worker__pb2.InitializeRunnerResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def execute_task(self, request: workflows_dot_v1_dot_core__pb2.Task, ctx: RequestContext) -> workflows_dot_v1_dot_worker__pb2.ExecuteTaskResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def shutdown_worker(self, request: google_dot_protobuf_dot_empty__pb2.Empty, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class WorkerServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: WorkerServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/workflows.v1.WorkerService/ListRegisteredTasks": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListRegisteredTasks",
                        service_name="workflows.v1.WorkerService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=workflows_dot_v1_dot_core__pb2.TaskIdentifiers,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_registered_tasks,
                ),
                "/workflows.v1.WorkerService/InitializeWorker": EndpointSync.unary(
                    method=MethodInfo(
                        name="InitializeWorker",
                        service_name="workflows.v1.WorkerService",
                        input=workflows_dot_v1_dot_worker__pb2.InitializeRunnerRequest,
                        output=workflows_dot_v1_dot_worker__pb2.InitializeRunnerResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.initialize_worker,
                ),
                "/workflows.v1.WorkerService/ExecuteTask": EndpointSync.unary(
                    method=MethodInfo(
                        name="ExecuteTask",
                        service_name="workflows.v1.WorkerService",
                        input=workflows_dot_v1_dot_core__pb2.Task,
                        output=workflows_dot_v1_dot_worker__pb2.ExecuteTaskResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.execute_task,
                ),
                "/workflows.v1.WorkerService/ShutdownWorker": EndpointSync.unary(
                    method=MethodInfo(
                        name="ShutdownWorker",
                        service_name="workflows.v1.WorkerService",
                        input=google_dot_protobuf_dot_empty__pb2.Empty,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.shutdown_worker,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/workflows.v1.WorkerService"


class WorkerServiceClientSync(ConnectClientSync):
    def list_registered_tasks(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_core__pb2.TaskIdentifiers:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRegisteredTasks",
                service_name="workflows.v1.WorkerService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=workflows_dot_v1_dot_core__pb2.TaskIdentifiers,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def initialize_worker(
        self,
        request: workflows_dot_v1_dot_worker__pb2.InitializeRunnerRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_worker__pb2.InitializeRunnerResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="InitializeWorker",
                service_name="workflows.v1.WorkerService",
                input=workflows_dot_v1_dot_worker__pb2.InitializeRunnerRequest,
                output=workflows_dot_v1_dot_worker__pb2.InitializeRunnerResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def execute_task(
        self,
        request: workflows_dot_v1_dot_core__pb2.Task,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> workflows_dot_v1_dot_worker__pb2.ExecuteTaskResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ExecuteTask",
                service_name="workflows.v1.WorkerService",
                input=workflows_dot_v1_dot_core__pb2.Task,
                output=workflows_dot_v1_dot_worker__pb2.ExecuteTaskResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def shutdown_worker(
        self,
        request: google_dot_protobuf_dot_empty__pb2.Empty,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ShutdownWorker",
                service_name="workflows.v1.WorkerService",
                input=google_dot_protobuf_dot_empty__pb2.Empty,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
