name: Publish Tilebox Workflows

on:
  release:
    types: [published]

jobs:
  release:
    name: Build and Publish Tilebox Workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for checkout
      id-token: write # required trusted publishing to pypi.org
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Print version
        run: git describe --tags
      - name: Build
        run: mkdir dist && uv run python -m build tilebox-workflows && mv tilebox-workflows/dist/* dist/
      - name: Publish to PyPi.org
        if: github.event_name == 'release'
        # authorization is done via OIDC, so we don't need to specify a token
        # Instead, we've set up a trusted publishing config on pypi.org, that maps to this repository and the
        # publish_tilebox_workflows workflow and maps it to the tilebox-workflows package on pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
